import { AiFillStar } from "react-icons/ai";
export const productObj = [
  {
    id: 1,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0001802-211xauto.png",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US10", "US9", "US12"],
  },
  {
    id: 2,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0002491-211xauto.png",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 3,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0001814-211xauto.png",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 4,
    img: "https://pngfre.com/wp-content/uploads/Shoes-2-1024x579.png",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 5,
    img: "https://freepngimg.com/thumb/shoes/26263-3-nike-shoes-transparent-image-thumb.png",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "indigo"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 6,
    img: "https://www.pngmart.com/files/21/Adidas-Shoes-PNG-Picture.png",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },

  {
    id: 7,
    img: "https://pngimg.com/d/converse_PNG14.png",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 8,
    img: "https://freepngimg.com/thumb/shoes/21849-6-dock-shoes-thumb.png",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 9,
    img: "https://pngimg.com/d/running_shoes_PNG5827.png",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 10,
    img: "https://static.vecteezy.com/system/resources/thumbnails/009/664/905/small/3d-render-sport-shoes-illustration-png.png",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 11,
    img: "https://api.time.com/wp-content/uploads/2016/01/150811-gemini26325.png",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 12,
    img: "https://static.nike.com/a/images/t_default/cad91927-b07b-47c9-a44a-e433b1349d1c/ja-1-hunger-basketball-shoes-bCx2W3.png",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 13,
    img: "https://assets.origami-02-prod-1ot7.decathlon.io/e12b5d4673eab895d836485c75f7ccfc/landings/MH500/assets/img/mid-woman-1.webp",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 14,
    img: "https://images.ctfassets.net/hnk2vsx53n6l/vZC3OfrjGoIBakuaXzd7E/f48adb9aa05d260ddf0f40d9d0d84355/d20b1a18afce59ed4f6515826fc46fce02543c94.png?fm=webp",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 15,
    img: "https://freepngimg.com/thumb/categories/1498.png",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 16,
    img: "https://images.ctfassets.net/hnk2vsx53n6l/1wdCZaw77vBgD8JUS5hG4d/ad406863ab7fa3961bdf8c0f3a0d4a63/01aedf81ce3cc81b6e0a9bbffb737c0b4a9892a3.png?fm=webp",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 17,
    img: "https://images.ctfassets.net/hnk2vsx53n6l/2S88D3z7ZZ9mQm0VT5gpIv/86e3770dcb1d8d5ec0c78334e99cd3f1/qajt34xixl9w0hixisdf.png?fm=webp",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 18,
    img: "https://pngfre.com/wp-content/uploads/Shoes-4-1024x615.png",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 19,
    img: "https://pngimg.com/d/running_shoes_PNG5813.png",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
  {
    id: 20,
    img: "https://i.pinimg.com/originals/9a/06/a9/9a06a9d5fb3daddd463ae7f84b82904f.png",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    qty: 1,
    likedProduct: false,
    availableProductColors: ["red", "yellow", "pink", "blue"],
    availableProductSize: ["US6", "US7", "US9", "US12"],
  },
];
