import { AiFillStar } from "react-icons/ai";
export const productObj = [
  {
    id: 1,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0001802-211xauto.png",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 2,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0002491-211xauto.png",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },

  {
    id: 3,
    img: "https://images.hhbrown.com/Dexter%20Bowling/Single/DP0001814-211xauto.png",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 4,
    img: "https://cdn.shakedeal.com/images/detailed/623/SDCZN0000100_bb5n-nq.png?t=1603793113",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 5,
    img: "https://freepngimg.com/thumb/shoes/26263-3-nike-shoes-transparent-image-thumb.png",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 6,
    img: "https://freepngimg.com/thumb/shoes/26252-8-black-shoe-image-thumb.png",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    qty: 1,
    likedProduct: false,
  },

  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
    qty: 1,
    likedProduct: false,
  },

  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },

  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },

  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
    qty: 1,
    likedProduct: false,
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats",
    qty: 1,
    likedProduct: false,
  },
  // {
  //   id: 18,
  //   img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
  //   title: "Vans Unisex Low-Top",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "blue",
  //   category: "flats",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 19,
  //   img: "https://m.media-amazon.com/images/I/812Jk2G+yPL._SX695_.jpg",
  //   title: "Classic Bandana Sandals",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "50",
  //   company: "Nike",
  //   color: "black",
  //   category: "sandals",
  //   qty: 1,
  //   likedProduct: false,
  // },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
    qty: 1,
    likedProduct: false,
  },
  // {
  //   id: 21,
  //   img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
  //   title: "Slip On Stiletto High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "100",
  //   company: "puma",
  //   color: "black",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 22,
  //   img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
  //   title: "DREAM PAIRS Court Shoes",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "150",
  //   company: "Nike",
  //   color: "red",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  {
    id: 23,
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "14000",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    qty: 1,
    likedProduct: false,
  },

  // {
  //   id: 24,
  //   img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
  //   title: "Low Mid Block Heels",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "black",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 25,
  //   img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 26,
  //   img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
  //   title: "Amore Fashion Stilettos",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "150",
  //   company: "Adidas",
  //   color: "white",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 27,
  //   img: "https://freepngimg.com/thumb/women%20shoes/1-women-shoes-png-image-thumb.png",
  //   title: "Bridal Sandals Glitter",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   qty: 1,
  //   likedProduct: false,
  // },
  // {
  //   id: 28,
  //   img: "https://freepngimg.com/thumb/women%20shoes/3-women-shoes-png-image-thumb.png",
  //   title: "Wedding Prom Bridal",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "14000",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "flats",
  //   qty: 1,
  //   likedProduct: false,
  // },
];
